### ISSUE TITLE
Langue pour Acknowledge sticky et persistent

### ISSUE THREAD

**Issue by Jm0u** [ddurieux/glpi_monitoring#133]
Mettre les informations en français pour les non initiés

**Comment by mohierf** [comment]
C'est un peu compliqué ... car c'est le jargon "métier". et je ne crois pas que mettre "collant" au lieu de sticky soit beaucoup plus parlant ?

**Comment by ddurieux** [comment]
Assez d'accord, j'ai essayé 2 ou 3 fois de réfléchir sur ce ticket pour trouver de bonnes traductions, mais impossible d'en trouver :p

**Comment by mohierf** [comment]
Close ?

**Comment by kiniou** [comment]
Vous pouvez utiliser le terme "épinglé" pour "sticky" comme pour une discussion de forum qui est toujours visible en première page..

**Comment by Sismic** [comment]
excellente idée

**Comment by mohierf** [comment]
+1 pour épinglé !

**Comment by ddurieux** [comment]
Traduit sur transifex
