### ISSUE TITLE
Page Dashboard qui "disparait"

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#139]
Bonjour,

J'ai un petit soucis avec le plugin Monitoring, que j'avais avec la version 0.84+1.0 et que j'ai aussi avec la version 0.84+2.0b (suite à l'issue ouverte ici https://github.com/shinken-monitoring/mod-import-glpi/issues/2 qui a été résolue.)

Lorsque je rajoute quelque chose dans mon catalogue composant (composant ou hôte) je me retrouve avec une page blanche lorsque je retourne sur le tableau de bord (dashboard). J'ai les menus glpi, mais en dessous c'est blanc. Le seul moyen de retourner à la normale est de redémarrer Shinken directement sur la Linux (service shinken restart). Et cela revient ensuite.

Serveur : Debian 7 
GLPI (0.84.8)
      - Services Web (1.4.3),
      - Monitoring(0.84+2.0b), 
      - OCS Inventory NG (1.0.3).
Shinken 2.2
      - import-glpi, glpidb, ws-arbiter, webui

   Exemple après rajout d'un composant : 

![image](https://cloud.githubusercontent.com/assets/8926922/7062310/4082020c-de9c-11e4-90a4-fbb14d939934.png)

Est-ce que cela vient du plugin ? Ou c'est dû au mauvais redémarrage de Shinken (trop souvent, trop vite ?)

**Comment by ddurieux** [comment]
If you have blank page, see apache error file and search if you have PHP error

**Comment by algorys** [comment]
Ok,

Here are the log I have : 

tail -f /var/log/apache2/access
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/plugins/monitoring/lib/jqueryplugins/jquery-tagbox/js/jquery.tagbox.js HTTP/1.1" 304 211 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/css/print.css HTTP/1.1" 304 211 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/lib/tiny_mce/tiny_mce.js HTTP/1.1" 304 212 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/plugins/monitoring/lib/jquery/js/jquery-1.8.3.js HTTP/1.1" 304 212 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/css/tab-scroller-menu.css HTTP/1.1" 304 210 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/menu_add_off.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/menu_search_off.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/menu_all.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/bookmark.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/search.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "GET /glpi/pics/menu_config.png HTTP/1.1" 304 187 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
192.168.1.139 - - [09/Apr/2015:10:07:32 +0200] "POST /glpi/plugins/monitoring/ajax/updateshinkenrestartmessage.php HTTP/1.1" 200 387 "http://dev03/glpi/plugins/monitoring/front/menu.php" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
::1 - - [09/Apr/2015:10:07:40 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.2.22 (Debian) (internal dummy connection)"

And I see no error...

**Comment by ddurieux** [comment]
It's the access file, not error file :p

**Comment by Sismic** [comment]
version of php ?

**Comment by algorys** [comment]
Oops sorry. it's morning, I'm still not awake.

Here is the good log : 

[Thu Apr 09 09:39:25 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/
[Thu Apr 09 09:51:52 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/front/menu.php
[Thu Apr 09 09:52:14 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/front/menu.php
[Thu Apr 09 09:52:15 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/front/menu.php
[Thu Apr 09 10:02:35 2015] [error] [client 192.168.1.132] File does not exist: /var/www/favicon.ico
[Thu Apr 09 10:05:04 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/front/componentscatalog_component.form.php
[Thu Apr 09 10:05:09 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/
[Thu Apr 09 10:06:11 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/
[Thu Apr 09 10:06:36 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/
[Thu Apr 09 10:07:32 2015] [error] [client 192.168.1.139] PHP Fatal error:  Call to undefined function curl_init() in /var/www/glpi/plugins/monitoring/inc/shinkenwebservice.class.php on line 205, referer: http://dev03/glpi/plugins/monitoring/

**Comment by ddurieux** [comment]
You need install and load php module CURL

**Comment by algorys** [comment]
That's ok. apt-get install php5-curl and it's gone. Thanks.

**Comment by algorys** [comment]
Sorry, but still an error.

I have something like that now, after add a new "composant" : 

 La communication avec Shinken a échoué : IPv6 numerical address used in URL without brackets
http://::1:7760/reload 

But I do not configure some IPv6 on my server...

You know if there a way to remove that ?

**Comment by ddurieux** [comment]
see in menu plugin monitoring > tags

**Comment by algorys** [comment]
Thanks @ddurieux I close issue.
