### ISSUE TITLE
Check disk different hosts

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#140]
Hello,

Me again (I want to post like a question, but can't find how to do that)

Now I have a monitoring who works, I'm playing with it :+1: But I encountered some problem. I'm trying just to get a disk monitoring first, so I have make something like that in my command file : 

![image](https://cloud.githubusercontent.com/assets/8926922/7068160/cb4c91ac-ded0-11e4-83fc-9604a4c1827a.png)

But it seems he give me only the space of the disk of the server. How I can make that for other hosts please ?

**Comment by Sismic** [comment]
http://www.glpi-project.org/forum/viewforum.php?id=8

**Comment by algorys** [comment]
ok, sorry for the inconvenience.
