### ISSUE TITLE
No possibility to save argument

### ISSUE THREAD

**Issue by Sismic** [ddurieux/glpi_monitoring#143]
Hi David, no button ta save configuration for specific arguments

![capture](https://cloud.githubusercontent.com/assets/6815687/7230164/88aabe8e-e76b-11e4-97a8-667c0ddcb623.JPG)

**Comment by ddurieux** [comment]
Check if you have right in profile (tab monitoring)

**Comment by Sismic** [comment]
in profile, all rights are checked. 
![capture](https://cloud.githubusercontent.com/assets/6815687/7231938/f45b3eda-e778-11e4-9ff4-fc773ecf8a92.JPG)

**Comment by Sismic** [comment]
Hi David, any idea about this issue ?

**Comment by ddurieux** [comment]
Oh yes, see in apache error log, I think you have a PHP fatal error message

**Comment by Sismic** [comment]
oh, no php fatal error appears :( and from access.log:

128.15.2.138 - - [22/Apr/2015:15:22:26 +0200] "GET /glpi/plugins/monitoring/front/servicearg.form.php?id=876 HTTP/1.1" 200 5203 "http://glpi.plastibell.com/glpi/front/computer.form.php?id=11" "Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0"

128.15.2.138 - - [22/Apr/2015:15:22:26 +0200] "GET /glpi/plugins/formcreator/scripts/scripts.js.php HTTP/1.1" 200 2430 "http://glpi.plastibell.com/glpi/plugins/monitoring/front/servicearg.form.php?id=876" "Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0"

**Comment by ddurieux** [comment]
And in log errors of GLPI ?

**Comment by Sismic** [comment]
2015-04-22 15:27:33 [26@PLAGLPI001]
  *** PHP Notice(8): Undefined index:
  Backtrace :
  plugins/monitoring/inc/hostconfig.class.php:263
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringHostconfig->showForm()
  inc/commonglpi.class.php:455                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:87                            CommonGLPI::displayStandardTab()

Erros appears when i see all ressources from a server, no error appears when i want to configure arguments

**Comment by ddurieux** [comment]
Ok I see the problem, I will fix it ;)
