### ISSUE TITLE
component catalog view for a computer: missmatch with configuration

### ISSUE THREAD

**Issue by Sismic** [ddurieux/glpi_monitoring#154]
a server (11) have 4 component catalog (Id:7,2,3,24) associated but from view RESSOURCES, a fifth catalog (ID: 6) appears.
![capture](https://cloud.githubusercontent.com/assets/6815687/7389974/82b29916-ee73-11e4-9542-feb1cc8977f9.JPG)

list of items_id associate to plugin_monitoring_componentscalalog_id=6:
![capture](https://cloud.githubusercontent.com/assets/6815687/7389997/c213173e-ee73-11e4-853e-13ec349e2bb6.JPG)

original view 
![capture](https://cloud.githubusercontent.com/assets/6815687/7390013/f12a0b7c-ee73-11e4-98ab-d332afad7c2e.JPG)

**Comment by ddurieux** [comment]
I have found, it search computer id LIKE "%11%" instead id = "11", so it found for computer with id 211 because it contain "11". Now it's better ;)
