### ISSUE TITLE
Blank page when installed

### ISSUE THREAD

**Issue by mickythekiller** [ddurieux/glpi_monitoring#156]
Hi,
when i install this plugin 0.85+ on 0.85.3 i have a blank page on glpi and i must desactivate it
thanks

**Comment by ddurieux** [comment]
See fatal errors in apache error logs

**Comment by mickythekiller** [comment]
no error

**Comment by ddurieux** [comment]
and errors in glpi logs?

**Comment by mickythekiller** [comment]
nothing

**Comment by Sismic** [comment]
version of php ?

**Comment by mickythekiller** [comment]
Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1

**Comment by ddurieux** [comment]
Try with last version of the repository, I think it's fixed

**Comment by mickythekiller** [comment]
Same issue with 27/04/2015 version

**Comment by ddurieux** [comment]
And with dev version in github?

**Comment by mickythekiller** [comment]
nice! thanks !

**Comment by ddurieux** [comment]
It's ok ?

**Comment by mickythekiller** [comment]
Yes! ok!
