### ISSUE TITLE
monitoring install from 11.05.15: error found in /php-errors.log

### ISSUE THREAD

**Issue by Sismic** [ddurieux/glpi_monitoring#164]
with lastest monitoring install this morning:

2015-05-11 08:35:03 [170@PLAGLPI001]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  ...lugins/monitoring/inc/hostaddress.class.php:191
  ...pi/plugins/monitoring/inc/shinken.class.php:544 PluginMonitoringHostaddress::getIp()
  ...plugins/monitoring/inc/webservice.class.php:152 PluginMonitoringShinken->generateHostsCfg()
  :                                                  PluginMonitoringWebservice::methodShinkenHosts()
  ...ins/webservices/inc/methodsession.class.php:496 call_user_func()
  /var/www/glpi/plugins/webservices/xmlrpc.php:99    PluginWebservicesMethodSession->execute()
2015-05-11 08:35:10 [170@PLAGLPI001]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  ...lugins/monitoring/inc/hostaddress.class.php:191
  ...pi/plugins/monitoring/inc/shinken.class.php:544 PluginMonitoringHostaddress::getIp()
  ...plugins/monitoring/inc/webservice.class.php:152 PluginMonitoringShinken->generateHostsCfg()
  :                                                  PluginMonitoringWebservice::methodShinkenHosts()
  ...ins/webservices/inc/methodsession.class.php:496 call_user_func()
  /var/www/glpi/plugins/webservices/xmlrpc.php:99    PluginWebservicesMethodSession->execute()

**Comment by ddurieux** [comment]
Fixed yesterday
