### ISSUE TITLE
Improvements : various proposals

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#178]
Hello,

I use this plugin and that's a wonderfull plugin :)

I have some ideas for more facility to use : 

1 - Add possibility to add contact's catalog in mass with the action button. At this moment we can only modify comments and if we have to add or remove someone, we have to make on each catalogs.

2 - Can we have the possibility of display View or Slider directly on the front page of Dashboard. Instead of click on each at this page (monitoring/front/dashboard.php) ?

3 - Improve the save of graphics, because if we click on return or refresh the page (on Chrome), the save of value is not take at each time... or it return to default...

Thanks for your hard work and the help you give at each time :)

**Comment by ddurieux** [comment]
Can you open an issue for each please? it will be more easier to have conversation ;)

**Comment by algorys** [comment]
I make it and close this issue.
