### ISSUE TITLE
ALERT of some plugins doesn't triggers notifications

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#179]
Hello,

I've noticed that some commands who changes to WARNING or CRITICAL doesn't triggers notifications. I'm not sure that's part of monitoring plugin or Shinken issue...

--> Here is some example :

SERVICE ALERT: routeur;currentconnections;CRITICAL;HARD;3;SNMP CRITICAL - 1098

Corresponding command :

./check_snmp -H $HOSTADDRESS$ -c public -o .1.3.6.1.4.1.8741.1.3.1.2.0 -w 800 -c 1000

--> Another example :

SERVICE ALERT: esx2;esx_net_receive;OK;SOFT;2;CHECK_VMWARE_API.PL OK - net receive=123.00 KBps

Corresponding command :

./check_vmware_api.pl -D $HOSTADDRESS$ -f auth.cfg -l vmfs -w 80% -c 90% -s BDD01 -o used

Is there some bug in monitoring plugins ?

Or the command doesn't works for notifications ?

Or it's due to Shinken ?

I must clarify that I receive another notifications from GLPI for another commands. Certains command send me notifications for some hosts and not for other. yet it is the exactly same command...

Does I missed something ?

Thanks for help.

GLPI 0.85.4
Monitoring 0.85.1
Shinken 2.4
Debian 7

**Comment by algorys** [comment]
Is this may be because I'm using the python script for the two template contact ?

**Comment by algorys** [comment]
It seems that SOFT alert doesn't triggers notifications, so is there a possibility to change that in a next version of plugins or not ?

**Comment by ddurieux** [comment]
not possible SOFT = not yet sure it's WARNING / CRITICAL, so if we have another WARNING / CRITICAL it will be HARD

**Comment by algorys** [comment]
Ok, thanks. So I close issue.
