### ISSUE TITLE
SQL Error update

### ISSUE THREAD

**Issue by Sismic** [ddurieux/glpi_monitoring#187]
0.85+1.1 multiple alter in glpi_plugin_monitoring_serviceevents - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_plugin_monitoring_serviceevents` DROP `output` - L'erreur est Can't DROP 'output'; check that column/key exists

**Comment by Sismic** [comment]
2015-06-23 15:38:00 [26@PLAGLPI001]
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_plugin_monitoring_serviceevents` DROP `output`
  Error: Can't DROP 'output'; check that column/key exists
  Backtrace :
  inc/dbmysql.class.php:201
  inc/migration.class.php:575                        DBmysql->queryOrDie()
  plugins/monitoring/install/update.php:3920         Migration->migrationOneTable()
  plugins/monitoring/install/update.php:2257         migrateTablesMonitoring()
  plugins/monitoring/hook.php:118                    pluginMonitoringUpdate()
  inc/plugin.class.php:639                           plugin_monitoring_install()
  front/plugin.form.php:45                           Plugin->install()

**Comment by ddurieux** [comment]
I think it's fixed in 0.90 version, if you have again the problem, create a new issue ;)
