### ISSUE TITLE
Improvement : improve graphics' s save on refresh page?

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#194]
Hello,

I use GLPI and I would like to propose an improvement :

Can you improve the save of graphics, because if we click on return or refresh the page (on Chrome), the save of value is not take at each time... or it return to default...

Many thanks

**Comment by ddurieux** [comment]
It's normal, configuration of graphs can be do in components catalog, and ao it's saved

**Comment by algorys** [comment]
Aaah, ok...

So I think I can close it.
