### ISSUE TITLE
Improvement : link between jenkins' s results and glpi_monitoring

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#195]
Hello,

I use your plugin and I want to know :

I don't know if it is possible but is your pkugin can receive some results of a jenkins server (with matrix, per example ? And display some graph of compilations ? 

Thanks for answer ?

**Comment by ddurieux** [comment]
Have you got an example of data jenkins?

**Comment by ddurieux** [comment]
You have scripts checks can get info from jenkins server
