### ISSUE TITLE
Shinken configuration Web services - tag not found ...

### ISSUE THREAD

**Issue by mohierf** [ddurieux/glpi_monitoring#200]
When Shinken requests configuration with a specified tag and this tag is not found in Glpi database, he WS sends the configuration for all the hosts in the database!

The logical behaviour should be to not send anything ... to avoid overloading Shinken!

**Comment by ddurieux** [comment]
Not reproduce this problem :/
Perhaps the tag is in table glpi_plugin_monitoring_entities but the entity linked has been deleted ?

**Comment by mohierf** [comment]
You are right ... it is possible. I had to add a `Demo`tag in my entity to fix my problem ...
