### ISSUE TITLE
Is there a 0.90 version expected

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#207]
Hello,

I want to know if there is a version for Glpi 0.90 planned in your Roadmap ?

thanks

**Comment by ddurieux** [comment]
Yes come soon

**Comment by algorys** [comment]
Ok, thanks for answer @ddurieux .

I'm waiting with impatience.

**Comment by ddurieux** [comment]
Sorry, I had changed house these last days, so return working on it ;)

**Comment by algorys** [comment]
Ok, no problem. Still wait ;)

**Comment by algorys** [comment]
Hello,

Is there any news for a 0.90+ version ?

**Comment by ddurieux** [comment]
Planned tomorrow ;)

**Comment by algorys** [comment]
Ok, thanks for rapid answer.

**Comment by algorys** [comment]
Thanks I try it but I encounter this problem #212
