### ISSUE TITLE
Upgrade 0.85 to 0.90 : blank field, wrond component name and jscolor does not exist

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#212]
Hello,

I've upgrade my installation of GLPI 0.85 to 0.90 and make upgrade plugin also.

The update works fine during plugin update, but now when I go to plugin Monitoring i've something like that on "Composants" : 

![image](https://cloud.githubusercontent.com/assets/8926922/13080658/f05c42c2-d4c9-11e5-9cba-7838fb6ccefe.png)

All fiel are sames... and resources state are blank. 

I should clarify that : 

- when I click the link of graphs it takes me to the right place but the link name is not the good one.
- when I click on component name (who is always the same), it takes me always to the same component

In my log of glpi : 

```
[Tue Feb 16 15:27:29 2016] [error] [client 192.168.1.182] File does not exist: /var/www/glpi/plugins/monitoring/front/jscolor, referer: http://glpi.alpi-net.com/plugins/monitoring/front/display.form.php?itemtype=PluginMonitoringService&items_id=4
[Tue Feb 16 15:27:29 2016] [error] [client 192.168.1.182] File does not exist: /var/www/glpi/plugins/monitoring/front/jscolor, referer: http://glpi.alpi-net.com/plugins/monitoring/front/display.form.php?itemtype=PluginMonitoringService&items_id=4

```

Is there something I miss ?

Thanks for help

**Comment by algorys** [comment]
I return to the old version for now...

**Comment by Sismic** [comment]
+1 i have same problem, for me the solution is to migrate to matser version of GLPI from github but it's beta version, not official ....

**Comment by ddurieux** [comment]
You used relesed version 0.90+1.0 of plugin ?

**Comment by Sismic** [comment]
I must revert to official version 0.90.1 because some bugs appears on GLPI. When it's done i will inform to you if it works or not.

**Comment by Sismic** [comment]
https://github.com/ddurieux/glpi_monitoring/issues/210

**Comment by algorys** [comment]
@ddurieux : yes it was 0.90+1.0 of plugin.

**Comment by algorys** [comment]
I've installed some another servers (Shinken 2.4.2 and GLPI 0.90.1) from scratch to test and I've the same `bug` for : 

* the `resource state` wich is not display.
* the `last control` column which is empty
* the `result` who is empty too...

I've no error on Shinken side and glpi side in my log... So maybe it's due to the new interface of GLPI ?

**Comment by Sismic** [comment]
Show in php-errors.log

  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: calendars_id
  Backtrace :
  plugins/monitoring/inc/display.class.php:1206
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/monitoring/inc/display.class.php:1077
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1087
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1088
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1089
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: graph_template
  Backtrace :
  plugins/monitoring/inc/component.class.php:648
  plugins/monitoring/inc/display.class.php:1104      PluginMonitoringComponent->hasPerfdata()
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 10
  Backtrace :
  plugins/monitoring/inc/display.class.php:1138
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: calendars_id
  Backtrace :
  plugins/monitoring/inc/display.class.php:1206
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/monitoring/inc/display.class.php:1077
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1087
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1088
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1089
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: graph_template
  Backtrace :
  plugins/monitoring/inc/component.class.php:648
  plugins/monitoring/inc/display.class.php:1104      PluginMonitoringComponent->hasPerfdata()
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 10
  Backtrace :
  plugins/monitoring/inc/display.class.php:1138
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: calendars_id
  Backtrace :
  plugins/monitoring/inc/display.class.php:1206
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/monitoring/inc/display.class.php:1077
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1087
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1088
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1089
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: graph_template
  Backtrace :
  plugins/monitoring/inc/component.class.php:648
  plugins/monitoring/inc/display.class.php:1104      PluginMonitoringComponent->hasPerfdata()
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 10
  Backtrace :
  plugins/monitoring/inc/display.class.php:1138
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-14 15:15:32 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined index: calendars_id
  Backtrace :
  plugins/monitoring/inc/display.class.php:1206
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()

**Comment by Sismic** [comment]
From a host:

2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:750
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:707
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:709
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1087
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1088
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1089
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:750
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:707
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:709
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1087
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1088
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1089
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 3
  Backtrace :
  plugins/monitoring/inc/display.class.php:1189
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/monitoring/inc/display.class.php:1192
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 4
  Backtrace :
  plugins/monitoring/inc/display.class.php:1198
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-14 15:18:26 [26@PLAGLPI001-DEV]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:750
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()

**Comment by algorys** [comment]
Exact ! I had forgotten these logs. I've same errors in `files/_log/php-errors.log`

```bash
2016-03-15 10:41:39 [2@srv-glpi]
  *** PHP Notice(8): Undefined offset: 5
  Backtrace :
  plugins/monitoring/inc/display.class.php:1202      
  plugins/monitoring/inc/display.class.php:740       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/front/service.php:116           PluginMonitoringDisplay->showResourcesBoard()
2016-03-15 10:42:42 [2@srv-glpi]
  *** PHP Notice(8): Undefined offset: 9
  Backtrace :
  plugins/monitoring/inc/display.class.php:1030      
  plugins/monitoring/front/host.php:106              PluginMonitoringDisplay->showHostsBoard()
```

And from host tabs : 

```bash
2016-03-15 10:45:42 [2@srv-glpi]
  *** PHP Notice(8): Undefined index: remotesystem
  Backtrace :
  plugins/monitoring/inc/display.class.php:1280      
  plugins/monitoring/inc/service.class.php:747       PluginMonitoringDisplay::displayLine()
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-03-15 10:45:42 [2@srv-glpi]
  *** PHP Notice(8): Undefined offset: 8
  Backtrace :
  plugins/monitoring/inc/service.class.php:750       
  plugins/monitoring/inc/service.class.php:614       PluginMonitoringService->listByHost()
  plugins/monitoring/inc/host.class.php:222          PluginMonitoringService->manageServices()
  inc/commonglpi.class.php:469                       PluginMonitoringHost::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
```

**Comment by Sismic** [comment]
Fix with GLPI 0.90.2

**Comment by ddurieux** [comment]
Cool, I close

**Comment by Jm0u** [comment]
Je confirme
