### ISSUE TITLE
Ajout de commande Sinken>GLPI

### ISSUE THREAD

**Issue by jbnitro** [ddurieux/glpi_monitoring#214]
Bonjour,

J'ai installé a nouveau shinken avec glpi_monitoring et j'ai quelques problèmes.
- j'ai l’état du système qui reste au rouge, j'avais réussi a la faire fonctionner sur une ancienne installation mais pas cette fois
- sinon pour l'ajout de commande est-ce qu'il y a une synchronisation entre shinken et glpi. 
Sur Shinken j'ai installé les packs windows et linux-snmp par exemple, 
sur l'interface de shinken elles sont bien reconnues mais sur GLPI j'ai rien, j'ai juste celle par défaut.
Donc faut il définir toutes les commandes directement depuis le menu command de monitoring ou est-ce qu'il y a un moyen d'ajouter les commandes qu'on installe avec shinken sur GLPI directement.
J'ai pas réussi a trouvé le fichier de configuration des commandes de GLPI

Merci

**Comment by ddurieux** [comment]
Pour le premier point, peut être un soucis avec le firewall, il teste le port 7770 

Pour le second, c'est uniquement GLPI => shinken pour la configuration. Il faut effectivement créer les commandes (Je n'ai pas fait de script d'import)

**Comment by Sismic** [comment]
Bonsoir, on pourrais p-e utiliser un partage ou une solution similaire permettant de mettre en commun nos fichiers de check et les commandes / graphs associés.

Cela permettrais de gagner pas mal de temps pour tout le monde.

P-e sur le wiki ici non ?

**Comment by jbnitro** [comment]
J'ai installer GLPI et Shinken sur la même machine et j'ai désactivé le firewall sur centos il me posait problème avec shinken déjà auparavant.

D'accord pas de soucis pour l'instant j'ai pas trop de commandes a faire, mais oui pourquoi pas partager un peu ses conf on gagnera du temps.

Parce que la si je mets la commande avec copier/coller depuis shinken vers glpi il ne prend pas en compte les argument donc Il faut quand même définir les hosts sur shinken ou on peut tout faire depuis glpi ?

**Comment by ddurieux** [comment]
Non le but c'est de TOUT configurer dans GLPI basé sur l'inventaire (pour les hosts)

**Comment by jbnitro** [comment]
D'accord, mais pour les ressources de shinken spécifique pour chaque host on les déclare ou ?
comme dans la commande 
`PLUGINSDIR$/check_wmi_plus.pl -H $HOSTADDRESS$ -u "$_HOSTDOMAINUSER$" -p "$_HOSTDOMAINPASSWORD$"`
j'ai bien modifié les lignes dans le dossier ressources sur shinken mais lors des check j'avais un accès refusé il ne faisait pas la correspondance

**Comment by Sismic** [comment]
Il faut créer des composants dédiés

**Comment by algorys** [comment]
Bonsoir,

Si vous patientez un peu je compte faire un tuto pour glpi et glpi_monitoring sur mon [blog](https://algorys.github.io) et mettre des commandes de bases pour les compostants.

Y'aura pas tout mais ce sera un début.

> Bonsoir, on pourrais p-e utiliser un partage ou une solution similaire permettant de mettre en commun nos fichiers de check et les commandes / graphs associés.

**Comment by jbnitro** [comment]
Bonsoir,

J'aimerais juste pour ma part une explication de comment ajouter des composants automatiquement par rapport a l'inventaire de fusion, et comment ajouter des commandes et services
Je commence tout juste a comprendre un peu le plugin

**Comment by ddurieux** [comment]
* Tu crée un composant (avec une commande, une période de check...)
* Tu crée un catalogue de composant avec un composant et au choix (ou les 2) l'ajout manuel des équipement (onglet static) ou via une règle de recherche GLPI (onglet règles). C'est ça qui associe l'inventaire de glpi / fusion avec les checks de supervision

Avec ça, tu devrais pouvoir faire ce que tu souhaites ;)

**Comment by jbnitro** [comment]
Merci j'ai réussi a configurer les premières commandes :)
Pour le problème de l’état système au rouge j'ai changé l'ip sur la conf de l'arbiter et c'est vert maintenant donc tout fonctionne
Mais j'ai l'impression que le reload automatique ne fonctionne pas je crois quand j'ajoute des composants et autres

Sinon pour les paramètres des commandes ou on les renseigne ?
`$PLUGINSDIR$/check_wmi_plus.pl -H $HOSTADDRESS$ -u "$_HOSTDOMAINUSER$" -p "$_HOSTDOMAINPASSWORD$" -m checkuptime -w '$_HOSTWINDOWS_REBOOT_WARN$' -c '$_HOSTWINDOWS_REBOOT_CRIT$' --inidir=$WMI_INI_DIR$`

parce que je trouve pas ou on peux le faire en définissant un composant spécifique

**Comment by ddurieux** [comment]
Le reload  automatique ne peut pas se faire si le dernier redémarrage auto date de moins de 5 minutes (ou 10 j'ai un doute)

Pour les paramètres, si tu ne veux pas les mettre dans GLPI, défini les dans le fichier de ressource de shinken, sinon tu remplace par des $ARG1$, $ARG2$... dans la commande puis tu peux mettre la valeur que tu veux dans le composant

**Comment by jbnitro** [comment]
J'ai l'impression que shinken ne prend pas en compte le fichier ressources j'ai bien tout configurer les paramètres des commandes mais rien j'ai toujours accès refusé

**Comment by jbnitro** [comment]
Bonjour,

Je reviens vers vous parce que j'ai un problème bizarre tout marchait depuis  nickel sans soucis et la je fait un shinken reload et plus rien l'arbiter ne veux plus démarrer j'ai des probleme item incorrect venant de import-glpi quand je désactive le module tout remarche ou quand j'importe aucune donnée de glpi tout va bien

> [1457711756] WARNING: [Shinken] [items] Host '_fake_BP_host' use/inherit from an unknown template ('fake') ! Imported from: module:import-glpi
[1457711756] WARNING: [Shinken] [items] the parent '_fake_Root' on host '_fake_BP_host' is unknown!
[1457711756] WARNING: [Shinken] [items] the parent '_fake_ecmorlaix' on host 'utyuyty0' is unknown!
[1457711756] WARNING: [Shinken] [items] the parent '_fake_ecmorlaix' on host 'tyutyut' is unknown!
[1457711756] WARNING: [Shinken] [items] the parent '_fake_ecmorlaix' on host 'tuy' is unknown!
[1457711756] WARNING: [Shinken] The host _fake_BP_host has no contacts nor contact_groups in (module:import-glpi)
[1457711756] WARNING: [Shinken] The host rtyututyu has no contacts nor contact_groups in (module:import-glpi)
[1457711756] ERROR: [Shinken] tryurtyu: my check_command None is invalid
[1457711756] ERROR: [Shinken] [items] In euetyuety is incorrect ; from module:import-glpi
[1457711756] WARNING: [Shinken] The host tyutyuty has no contacts nor contact_groups in (module:import-glpi)
[1457711756] ERROR: [Shinken] uuuuu: my check_command None is invalid
[1457711756] ERROR: [Shinken] [items] In ggggg is incorrect ; from module:import-glpi
[1457711756] WARNING: [Shinken] The host ggggg has no contacts nor contact_groups in (module:import-glpi)
[1457711756] ERROR: [Shinken] : my check_command None is invalid
[1457711756] ERROR: [Shinken] [items] In  is incorrect ; from module:import-glpi
[1457711756] ERROR: [Shinken]   hosts conf incorrect!!
[1457711756] INFO: [Shinken]    Checked 5 hosts
