### ISSUE TITLE
Display problem with ressources and metrics

### ISSUE THREAD

**Issue by henri-nourel** [ddurieux/glpi_monitoring#227]
Hi,

i have this problem in the display of ressources and metrics as you can see on theses screenshots.

- https://framapic.org/bAau7ehaPy1D/sB46AHuM7AWP.png
- https://framapic.org/Wbe9shDDiXyC/614Pdmkj5xzH.png
- https://framapic.org/7RuKFK8Y6Dcg/mJOmgZrlPLBv.png
- https://framapic.org/AnxxBxHIgo8n/siFeiQzvrjOa.png

i don't understand what is the problem, everything else is ok.

My configuration :
GLPI 0.91
Shinken 2.4.3
glpi_monitoring_0.90.1.1
Web services 1.6.0

**Comment by ddurieux** [comment]
glpi 0.91?

**Comment by henri-nourel** [comment]
glpi 0.90.1, excuse the mistake

**Comment by henri-nourel** [comment]
update to glpi 0.90.3, fix my problem.
